CREATE TABLE USUARIO(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	EMAIL			NVARCHAR(100)		NOT NULL UNIQUE,
	SENHA			NVARCHAR(50)		NOT NULL,
	PRIMARY KEY(ID))
GO

CREATE TABLE CATEGORIA(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(ID))
GO

CREATE TABLE CONTA(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	VALOR			DECIMAL(18,2)		NOT NULL,
	DATA			DATE				NOT NULL,
	OBSERVACOES		NVARCHAR(500)		NOT NULL,
	TIPO			INTEGER				NOT NULL,
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	IDCATEGORIA		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIA(ID))
GO



INSERT INTO USUARIO(ID, NOME, EMAIL, SENHA)
	VALUES (NEWID(), 'Jonas Monteiro', '13410453741', '04-01-23 10:34:09 AM', '1')

INSERT INTO CONTA (ID, NOME, VALOR, DATA, OBSERVACOES, TIPO, IDUSUARIO, IDCATEGORIA)
	VALUES (NEWID(), 'Rua X', 'numero 1500', 'Barra da Tijuca', 'Rio de Janeiro', 'RJ', '22775033', 'B8789234-62ED-4288-A1A5-8CC89BF0C479')

select * from USUARIO;
select * from CATEGORIA;
select * from CONTA;
				